import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {useStore,iso} from './store'
import {EventItem,Theme} from './types'
import {getJapaneseHoliday} from './holidays'
import './styles.css'
import './holiday-ui.css'

const dow=['月','火','水','木','金','土','日']
const cats:{key:EventItem['category'];label:string;icon:string}[]=[{key:'work',label:'仕事',icon:'◈'},{key:'personal',label:'個人',icon:'○'},{key:'health',label:'健康',icon:'♡'},{key:'study',label:'学習',icon:'△'}]
const fmt=(d:string)=>{const x=new Date(d+'T00:00:00');return `${x.getMonth()+1}月${x.getDate()}日（${['日','月','火','水','木','金','土'][x.getDay()]}）`}

function App(){
 const {events,settings,selectedDate,setSelectedDate,toggleDone,addEvent,updateEvent,deleteEvent,setTheme,setShowHolidays}=useStore();
 const [cursor,setCursor]=useState(()=>new Date()); const [modal,setModal]=useState<EventItem|Omit<EventItem,'id'|'completed'>|null>(null); const [settingsOpen,setSettingsOpen]=useState(false); const [toast,setToast]=useState('')
 useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.classList.toggle('reduced',settings.reducedMotion)},[settings])
 const days=useMemo(()=>{const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0);let lead=(first.getDay()+6)%7;if(!settings.weekStartsMonday)lead=first.getDay();const arr:(Date|null)[]=Array(lead).fill(null);for(let i=1;i<=last.getDate();i++)arr.push(new Date(y,m,i));while(arr.length%7)arr.push(null);return arr},[cursor,settings.weekStartsMonday])
 const monthEvents=events.filter(e=>e.date.startsWith(`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,'0')}`));
 const selected=events.filter(e=>e.date===selectedDate).sort((a,b)=>(a.start||'99').localeCompare(b.start||'99'))
 const selectedHoliday=settings.showHolidays?getJapaneseHoliday(selectedDate):null
 const done=monthEvents.filter(e=>e.completed).length,total=monthEvents.length,pct=total?Math.round(done/total*100):0
 const streak=calcStreak(events)
 const move=(n:number)=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+n,1))
 const today=iso(new Date())
 const select=(d:Date)=>{const s=iso(d);setSelectedDate(s)}
 const openNew=()=>setModal({title:'',date:selectedDate,start:'09:00',end:'10:00',memo:'',category:'work',priority:'normal'})
 const save=(e:EventItem|Omit<EventItem,'id'|'completed'>)=>{'id' in e?updateEvent(e):addEvent(e);setModal(null);setToast('予定を保存しました');setTimeout(()=>setToast(''),1800)}
 return <div className="app">
   <div className="ambient"/><header className="topbar">
    <button className="ghost today" onClick={()=>{const d=new Date();setCursor(new Date(d.getFullYear(),d.getMonth(),1));setSelectedDate(today)}}>今日</button>
    <div className="nav"><button onClick={()=>move(-1)}>‹</button><div className="month"><span>{cursor.getFullYear()}</span>{cursor.toLocaleString('ja-JP',{month:'long'})}</div><button onClick={()=>move(1)}>›</button></div>
    <div className="actions"><button className="icon" onClick={()=>setSettingsOpen(true)}>⚙</button><button className="primary add" onClick={openNew}>＋ <span>予定</span></button></div>
   </header>
   <section className="insights"><div><small>STREAK</small><strong>{streak}<em>日</em></strong></div><div><small>THIS MONTH</small><strong>{done}<em> / {total}</em></strong></div><div><small>FOCUS RATE</small><strong>{total?pct:'—'}<em>{total?'%':''}</em></strong></div><div className="quote">「ひとつ終わらせる。それだけで前に進んでいる。」</div></section>
   <main className="workspace">
    <section className="calendar-card"><div className="dow">{dow.map((x,i)=><span className={i>4?'weekend':''} key={x}>{x}</span>)}</div><div className="grid">{days.map((d,i)=>{const key=d?iso(d):`e${i}`, list=d?events.filter(e=>e.date===iso(d)):[];const active=d&&iso(d)===selectedDate, istoday=d&&iso(d)===today;const holiday=d&&settings.showHolidays?getJapaneseHoliday(iso(d)):null;return <button key={key} className={`day ${!d?'empty':''} ${active?'active':''} ${istoday?'today-cell':''} ${holiday?'holiday-day':''}`} onClick={()=>d&&select(d)}>{d&&<><div className="date-row"><span className="date">{d.getDate()}</span>{list.length>0&&<span className="count">{list.filter(e=>e.completed).length}/{list.length}</span>}</div>{holiday&&<div className="holiday-name" title={holiday.name}>{holiday.name}</div>}<div className="event-stack">{list.slice(0,3).map(e=><div key={e.id} className={`event-chip ${e.category} ${e.completed?'done':''}`}><span>{e.start||'終日'}</span>{e.title}</div>)}{list.length>3&&<div className="more">+{list.length-3} more</div>}</div></>}</button>})}</div></section>
    <aside className="agenda"><div className="agenda-head"><div><small>SELECTED DAY</small><h2>{fmt(selectedDate)}</h2>{selectedHoliday&&<div className="selected-holiday">● {selectedHoliday.name}</div>}</div><button className="round" onClick={openNew}>＋</button></div>{selected.length===0?<div className="empty-state"><div className="orb">✦</div><p>この日の予定はありません。</p><button onClick={openNew}>予定を追加する</button></div>:<div className="task-list">{selected.map(e=><TaskRow key={e.id} e={e} onToggle={()=>{toggleDone(e.id);if(!e.completed){setToast('✓ タスク完了！');setTimeout(()=>setToast(''),1600)}}} onEdit={()=>setModal(e)} />)}</div>}<div className="agenda-foot"><span>{selected.filter(e=>e.completed).length} 完了</span><span>{selected.length} 件</span></div></aside>
   </main>
   <nav className="bottom"><button className="selected">▦<span>カレンダー</span></button><button onClick={()=>setSelectedDate(today)}>◎<span>今日</span></button><button onClick={openNew}>＋<span>追加</span></button><button onClick={()=>setSettingsOpen(true)}>☰<span>設定</span></button></nav>
   {modal&&<EventModal value={modal} onClose={()=>setModal(null)} onSave={save} onDelete={'id' in modal?()=>{deleteEvent(modal.id);setModal(null)}:undefined}/>} {settingsOpen&&<Settings onClose={()=>setSettingsOpen(false)} theme={settings.theme} setTheme={setTheme} showHolidays={settings.showHolidays} setShowHolidays={setShowHolidays}/>} {toast&&<div className="toast">{toast}</div>}
 </div>
}
function TaskRow({e,onToggle,onEdit}:{e:EventItem;onToggle:()=>void;onEdit:()=>void}){return <div className={`task ${e.completed?'completed':''}`}><button className="check" onClick={onToggle}>{e.completed?'✓':''}</button><div className="task-main" onClick={onEdit}><div className="task-time">{e.start&&e.end?`${e.start} — ${e.end}`:'終日'} <span className={`priority ${e.priority}`}/></div><h3>{e.title}</h3>{e.memo&&<p>{e.memo}</p>}</div><button className="dots" onClick={onEdit}>•••</button></div>}
function EventModal({value,onClose,onSave,onDelete}:{value:EventItem|Omit<EventItem,'id'|'completed'>;onClose:()=>void;onSave:(e:any)=>void;onDelete?:()=>void}){const [v,setV]=useState(value);const set=(k:string,x:any)=>setV((p:any)=>({...p,[k]:x}));return <div className="overlay"><div className="sheet"><div className="sheet-head"><div><small>{'id'in v?'EDIT EVENT':'NEW EVENT'}</small><h2>{v.date}</h2></div><button onClick={onClose}>×</button></div><label>タイトル<input autoFocus value={v.title} onChange={e=>set('title',e.target.value)} placeholder="例：プレゼン準備"/></label><div className="two"><label>開始<input type="time" value={v.start||''} onChange={e=>set('start',e.target.value)}/></label><label>終了<input type="time" value={v.end||''} onChange={e=>set('end',e.target.value)}/></label></div><label>カテゴリ<div className="pills">{cats.map(c=><button className={v.category===c.key?'on':''} onClick={()=>set('category',c.key)} key={c.key}>{c.icon} {c.label}</button>)}</div></label><label>優先度<div className="pills">{(['low','normal','high'] as const).map(p=><button className={v.priority===p?'on':''} onClick={()=>set('priority',p)} key={p}>{p==='low'?'低':p==='normal'?'標準':'高'}</button>)}</div></label><label>メモ<textarea value={v.memo||''} onChange={e=>set('memo',e.target.value)} placeholder="詳細メモ…"/></label><div className="sheet-actions">{onDelete&&<button className="danger" onClick={onDelete}>削除</button>}<button className="primary save" disabled={!v.title.trim()} onClick={()=>onSave(v)}>保存する</button></div></div></div>}
function Settings({onClose,theme,setTheme,showHolidays,setShowHolidays}:{onClose:()=>void;theme:Theme;setTheme:(t:Theme)=>void;showHolidays:boolean;setShowHolidays:(v:boolean)=>void}){const themes:[Theme,string,string][]=[['violet','Violet','集中'],['sakura','Sakura','やさしい'],['ocean','Ocean','静か'],['ember','Ember','熱量'],['matrix','Matrix','レトロ']];return <div className="overlay"><div className="sheet settings"><div className="sheet-head"><div><small>FOCUSCAL</small><h2>設定</h2></div><button onClick={onClose}>×</button></div><section><small>CALENDAR</small><div className="setting-row"><div><b>日本の祝日を表示</b><p>カレンダー上に祝日名を表示します。</p></div><button className={`setting-toggle ${showHolidays?'on':''}`} role="switch" aria-checked={showHolidays} onClick={()=>setShowHolidays(!showHolidays)}><span/></button></div><p className="holiday-source">2026・2027年は内閣府公表日を収録。その他の年は現在の祝日法に基づいて表示します。</p></section><section><small>THEME</small><div className="theme-grid">{themes.map(t=><button key={t[0]} className={theme===t[0]?'theme-on':''} data-theme={t[0]} onClick={()=>setTheme(t[0])}><span/><b>{t[1]}</b><em>{t[2]}</em></button>)}</div></section><section><small>データ</small><div className="setting-row"><div><b>バックアップ</b><p>予定をJSONで書き出せます。</p></div><button onClick={()=>exportData()}>書き出す</button></div><div className="setting-row"><div><b>アプリをリセット</b><p>デモデータに戻します。</p></div><button className="danger-soft" onClick={()=>{if(confirm('データをリセットしますか？')){localStorage.removeItem('focuscal:v6');location.reload()}}}>リセット</button></div></section><p className="settings-note">UIを優先しながら、Task / Schedule / Completionを分離した構造で拡張していきます。</p></div></div>}
function exportData(){const raw=localStorage.getItem('focuscal:v6')||'{}';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([raw],{type:'application/json'}));a.download=`focuscal-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function calcStreak(events:EventItem[]){const days=new Set(events.filter(e=>e.completed).map(e=>e.date));let d=new Date();let n=0;while(days.has(iso(d))){n++;d.setDate(d.getDate()-1)}return n}
createRoot(document.getElementById('root')!).render(<App />)
